/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import javax.swing.JOptionPane;

/**
 *
 * @author Shashank Singh
 */
public class page3 extends javax.swing.JFrame {

    /**
     * Creates new form page3
     */
    public page3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        num2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        num3 = new javax.swing.JTextField();
        ac = new javax.swing.JRadioButton();
        nonac = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        list = new javax.swing.JComboBox<>();
        date = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("First Name");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 255));
        jLabel12.setText(" SPC Hotel Booking ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Last Name");

        name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("No. of people");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Check in Date");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Duration(Days)");

        ac.setText("Air-Conditioned");
        ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acActionPerformed(evt);
            }
        });

        nonac.setText("Non-Air-Conditioned");

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room Type", "Suite", "Single Bed", "Double Bed", "Deluxe ", "Super Deluxe" }));
        list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("No of Rooms");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(num3, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                            .addComponent(num2))
                                        .addGap(93, 93, 93)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ac)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jButton2)
                                                    .addComponent(nonac))
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton3))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(223, 223, 223))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name1)
                            .addComponent(jLabel2)
                            .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(ac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(nonac)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name2ActionPerformed

    private void acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acActionPerformed

    private void listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String fname = name1.getText();
                String lname = name2.getText();
                String date1 = date.getText();

                int b=Integer.parseInt(num3.getText());
                int a = Integer.parseInt(num2.getText());
                int c = Integer.parseInt(t1.getText());
                if(c<2){
                if(ac.isSelected()==true)
                {
                    String room = (String) list.getSelectedItem();
                if(room.equalsIgnoreCase("Suite"))
                {
                  if(b<10)  
                  JOptionPane.showMessageDialog(null,"Price is"+10000*a);
                  else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }
                }
                else if(room.equalsIgnoreCase("Single Bed")){
                    if(b<2)
                     JOptionPane.showMessageDialog(null,"Price is"+2000*a);
                     else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
                System.exit(0);
                  }}
                 else if(room.equalsIgnoreCase("Double Bed")){
                     if(b<4)
                     JOptionPane.showMessageDialog(null,"Price is"+3500*a);
                         else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }}
                 else if(room.equalsIgnoreCase("Deluxe")){
                     if(b<6)
                        JOptionPane.showMessageDialog(null,"Price is"+4900*a);
                        else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }}
                 else if(room.equalsIgnoreCase("Super Deluxe")){
                     if(b<8)
                       JOptionPane.showMessageDialog(null,"Price is"+6000*a);
                        else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }}

                lastpage p=new lastpage();
                p.setVisible(true);
                setVisible(false);
              JOptionPane.showMessageDialog(null,"Congratulation "+fname+" your booking for "+ b+" people "+" for "+a+" days" );
                                JOptionPane.showMessageDialog(null,"Booking details : AC "+room+"     Date :- "+date1);
                } else{      
                         String room = (String) list.getSelectedItem();
                if(room.equalsIgnoreCase("Suite"))
                {
                  if(b<10)  
                 JOptionPane.showMessageDialog(null,"Price is"+8000*a);
                      else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }
                }
                else if(room.equalsIgnoreCase("Single Bed")){
                    if(b<2)
                     JOptionPane.showMessageDialog(null,"Price is"+1500*a);
                      else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }}
                 else if(room.equalsIgnoreCase("Double Bed")){
                     if(b<4)
            JOptionPane.showMessageDialog(null,"Price is"+25000*a);
                         else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }}
                 else if(room.equalsIgnoreCase("Deluxe")){
                     if(b<6)
JOptionPane.showMessageDialog(null,"Price is"+3500*a);
                         else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }}
                 else if(room.equalsIgnoreCase("Super Deluxe")){
                     if(b<8)
                      JOptionPane.showMessageDialog(null,"Price is"+5000*a);
                        else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }}
                              JOptionPane.showMessageDialog(null,"Congratulation "+fname+" your booking for "+ b+" people "+" for "+a+" days" );
                                JOptionPane.showMessageDialog(null,"Booking details : AC "+room+"     Date :- "+date1);
     lastpage p=new lastpage();
                p.setVisible(true);
                setVisible(false);
                }    } 
                else{
                 if(ac.isSelected()==true)
                {
                    String room = (String) list.getSelectedItem();
                if(room.equalsIgnoreCase("Suite"))
                {
                  if(b<10*c)  
                 JOptionPane.showMessageDialog(null,"Price is"+10000*a*c);
                  else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }
                }
                else if(room.equalsIgnoreCase("Single Bed")){
                    if(b<2*c)
                    JOptionPane.showMessageDialog(null,"Price is"+2000*a*c);
                     else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
                System.exit(0);
                  }}
                 else if(room.equalsIgnoreCase("Double Bed")){
                     if(b<4*c)
                       JOptionPane.showMessageDialog(null,"Price is"+3500*a*c);
                         else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }}
                 else if(room.equalsIgnoreCase("Deluxe")){
                     if(b<6*c)
                       JOptionPane.showMessageDialog(null,"Price is"+4900*a*c);
                        else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }}
                 else if(room.equalsIgnoreCase("Super Deluxe")){
                     if(b<8*c)
                        JOptionPane.showMessageDialog(null,"Price is"+6000*a*c);
                        else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }}

                lastpage p=new lastpage();
                p.setVisible(true);
                setVisible(false);
              JOptionPane.showMessageDialog(null,"Congratulation "+fname+" your booking for "+ b+" people "+" for "+a+" days" );
                                JOptionPane.showMessageDialog(null,"Booking details : AC "+room+"     Date :- "+date1);
                } else{      
                         String room = (String) list.getSelectedItem();
                if(room.equalsIgnoreCase("Suite"))
                {
                  if(b<9*c)  
              JOptionPane.showMessageDialog(null,"Price is"+8000*a*c);
                      else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }
                }
                else if(room.equalsIgnoreCase("Single Bed")){
                    if(b<2*c)
                     JOptionPane.showMessageDialog(null,"Price is"+1500*a*c);
                      else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }}
                 else if(room.equalsIgnoreCase("Double Bed")){
                     if(b<4*c)
                        JOptionPane.showMessageDialog(null,"Price is"+2500*a*c);
                         else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }}
                 else if(room.equalsIgnoreCase("Deluxe")){
                     if(b<6*c)
                       JOptionPane.showMessageDialog(null,"Price is"+3500*a*c);
                         else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }}
                 else if(room.equalsIgnoreCase("Super Deluxe")){
                     if(b<7*c)
                       JOptionPane.showMessageDialog(null,"Price is"+5000*a*c);
                        else {
                      JOptionPane.showMessageDialog(null,"Not allowed to Book Room");
               System.exit(0);
                  }}
                              JOptionPane.showMessageDialog(null,"Congratulation "+fname+" your booking for "+ b+" people "+" for "+a+" days" );
                                JOptionPane.showMessageDialog(null,"Booking details : AC "+room+"     Date :- "+date1);
 lastpage p=new lastpage();
                p.setVisible(true);
                setVisible(false);
                }    
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          name1.setText(" ");
        name2.setText(" ");
        date.setText(" ");
        
        num2.setText(" ");
        num3.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page3().setVisible(true);
            }
        });}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ac;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> list;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField name2;
    private javax.swing.JRadioButton nonac;
    private javax.swing.JTextField num2;
    private javax.swing.JTextField num3;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
